-- -------------------------------------------------------------------------------
-- This file has been automatically generated by the Caph compiler (version 2.8.5)
-- from file main.cph, on 2020-02-19 at 21:55:37, by <unknown>
-- For more information, see : http://caph.univ-bpclermont.fr
-- -------------------------------------------------------------------------------

library ieee,caph;
use ieee.std_logic_1164.all;
use caph.core.all;
use caph.data_types.all;
use ieee.numeric_std.all;

entity dup_act is
   port (
    i_empty: in std_logic;
    i: in std_logic_vector(7 downto 0);
    i_rd: out std_logic;
    o1_full: in std_logic;
    o1: out std_logic_vector(7 downto 0);
    o1_wr: out std_logic;
    o2_full: in std_logic;
    o2: out std_logic_vector(7 downto 0);
    o2_wr: out std_logic;
    clock: in std_logic;
    reset: in std_logic
    );
end dup_act;

architecture FSM of dup_act is
begin
  comb: process(i, i_empty, o1_full, o2_full)
    variable p_x : unsigned(7 downto 0);
  begin
    -- i.rdy, o2.rdy, o1.rdy / p_x=i, wr(o1,p_x), wr(o2,p_x)
    if i_empty='0' and o2_full='0' and o1_full='0' then
      p_x := from_std_logic_vector(i,8);
      i_rd <= '1';
      o1 <= std_logic_vector(p_x);
      o1_wr <= '1';
      o2 <= std_logic_vector(p_x);
      o2_wr <= '1';
    else
      i_rd <= '0';
      o1_wr <= '0';
      o2_wr <= '0';
      o1 <= (others => 'X');
      o2 <= (others => 'X');
    end if;
  end process;
  seq: process(clock, reset)
  begin
    if (reset='0') then
    elsif rising_edge(clock) then
    end if;
  end process;
end FSM;
