-- -------------------------------------------------------------------------------
-- This file has been automatically generated by the Caph compiler (version 2.8.5)
-- from file main.cph, on 2020-02-19 at 21:55:37, by <unknown>
-- For more information, see : http://caph.univ-bpclermont.fr
-- -------------------------------------------------------------------------------

library ieee,caph;
use ieee.std_logic_1164.all;
use caph.core.all;
use caph.data_types.all;
use ieee.numeric_std.all;

entity inc_act is
   port (
    i_empty: in std_logic;
    i: in std_logic_vector(7 downto 0);
    i_rd: out std_logic;
    o_full: in std_logic;
    o: out std_logic_vector(7 downto 0);
    o_wr: out std_logic;
    clock: in std_logic;
    reset: in std_logic
    );
end inc_act;

architecture FSM of inc_act is
begin
  comb: process(i, i_empty, o_full)
    variable p_x : unsigned(7 downto 0);
  begin
    -- i.rdy, o.rdy / p_x=i, wr(o,p_x+1)
    if i_empty='0' and o_full='0' then
      p_x := from_std_logic_vector(i,8);
      i_rd <= '1';
      o <= std_logic_vector((p_x) + (to_unsigned(1,8)));
      o_wr <= '1';
    else
      i_rd <= '0';
      o_wr <= '0';
      o <= (others => 'X');
    end if;
  end process;
  seq: process(clock, reset)
  begin
    if (reset='0') then
    elsif rising_edge(clock) then
    end if;
  end process;
end FSM;
