-- -------------------------------------------------------------------------------
-- This file has been automatically generated by the Caph compiler (version 2.8.5)
-- from file main.cph, on 2020-02-19 at 21:55:37, by <unknown>
-- For more information, see : http://caph.univ-bpclermont.fr
-- -------------------------------------------------------------------------------

library ieee,caph;
use ieee.std_logic_1164.all;
use caph.core.all;
use caph.data_types.all;
use ieee.numeric_std.all;

entity main_net is
  port (
    w7_f: out std_logic;
    w7: in std_logic_vector(7 downto 0);
    w7_wr: in std_logic;
    w18_e: out std_logic;
    w18: out std_logic_vector(7 downto 0);
    w18_rd: in std_logic;
    clock: in std_logic;
    reset: in std_logic
    );
end main_net;

architecture arch of main_net is

component dup_act is
   port (
    i_empty: in std_logic;
    i: in std_logic_vector(7 downto 0);
    i_rd: out std_logic;
    o1_full: in std_logic;
    o1: out std_logic_vector(7 downto 0);
    o1_wr: out std_logic;
    o2_full: in std_logic;
    o2: out std_logic_vector(7 downto 0);
    o2_wr: out std_logic;
    clock: in std_logic;
    reset: in std_logic
    );
end component;


component mul_act is
   port (
    i1_empty: in std_logic;
    i1: in std_logic_vector(7 downto 0);
    i1_rd: out std_logic;
    i2_empty: in std_logic;
    i2: in std_logic_vector(7 downto 0);
    i2_rd: out std_logic;
    o_full: in std_logic;
    o: out std_logic_vector(7 downto 0);
    o_wr: out std_logic;
    clock: in std_logic;
    reset: in std_logic
    );
end component;


component dec_act is
   port (
    i_empty: in std_logic;
    i: in std_logic_vector(7 downto 0);
    i_rd: out std_logic;
    o_full: in std_logic;
    o: out std_logic_vector(7 downto 0);
    o_wr: out std_logic;
    clock: in std_logic;
    reset: in std_logic
    );
end component;


component inc_act is
   port (
    i_empty: in std_logic;
    i: in std_logic_vector(7 downto 0);
    i_rd: out std_logic;
    o_full: in std_logic;
    o: out std_logic_vector(7 downto 0);
    o_wr: out std_logic;
    clock: in std_logic;
    reset: in std_logic
    );
end component;



signal w17_f : std_logic;
signal w17 : std_logic_vector(7 downto 0);
signal w17_wr : std_logic;
signal w15_f : std_logic;
signal w15 : std_logic_vector(7 downto 0);
signal w15_wr : std_logic;
signal w16_e : std_logic;
signal w16 : std_logic_vector(7 downto 0);
signal w16_rd : std_logic;
signal w13_f : std_logic;
signal w13 : std_logic_vector(7 downto 0);
signal w13_wr : std_logic;
signal w14_e : std_logic;
signal w14 : std_logic_vector(7 downto 0);
signal w14_rd : std_logic;
signal w11_f : std_logic;
signal w11 : std_logic_vector(7 downto 0);
signal w11_wr : std_logic;
signal w12_e : std_logic;
signal w12 : std_logic_vector(7 downto 0);
signal w12_rd : std_logic;
signal w9_f : std_logic;
signal w9 : std_logic_vector(7 downto 0);
signal w9_wr : std_logic;
signal w10_e : std_logic;
signal w10 : std_logic_vector(7 downto 0);
signal w10_rd : std_logic;
signal w8_e : std_logic;
signal w8 : std_logic_vector(7 downto 0);
signal w8_rd : std_logic;

begin
  F12: fifo_small generic map (4,8) port map(w17_f,w17,w17_wr,w18_e,w18,w18_rd,clock,reset);
  F11: fifo_small generic map (4,8) port map(w15_f,w15,w15_wr,w16_e,w16,w16_rd,clock,reset);
  F10: fifo_small generic map (4,8) port map(w13_f,w13,w13_wr,w14_e,w14,w14_rd,clock,reset);
  F9: fifo_small generic map (4,8) port map(w11_f,w11,w11_wr,w12_e,w12,w12_rd,clock,reset);
  F8: fifo_small generic map (4,8) port map(w9_f,w9,w9_wr,w10_e,w10,w10_rd,clock,reset);
  F7: fifo_small generic map (4,8) port map(w7_f,w7,w7_wr,w8_e,w8,w8_rd,clock,reset);
  B3: dup_act  port map(w8_e,w8,w8_rd,w9_f,w9,w9_wr,w11_f,w11,w11_wr,clock,reset);
  B4: inc_act  port map(w10_e,w10,w10_rd,w13_f,w13,w13_wr,clock,reset);
  B5: dec_act  port map(w12_e,w12,w12_rd,w15_f,w15,w15_wr,clock,reset);
  B6: mul_act  port map(w14_e,w14,w14_rd,w16_e,w16,w16_rd,w17_f,w17,w17_wr,clock,reset);
end arch;
