-- -------------------------------------------------------------------------------
-- This file has been automatically generated by the Caph compiler (version 2.8.5)
-- from file main.cph, on 2020-05-06 at 15:29:19, by <unknown>
-- For more information, see : http://caph.univ-bpclermont.fr
-- -------------------------------------------------------------------------------

library ieee,caph;
use ieee.std_logic_1164.all;
use caph.core.all;
use caph.data_types.all;
use ieee.numeric_std.all;

package dc_s12 is
  function is_soS(t: std_logic_vector) return boolean;
  function is_eoS(t: std_logic_vector) return boolean;
  function is_data(t: std_logic_vector) return boolean;
  constant mk_soS: std_logic_vector(13 downto 0) := "01" & to_std_logic_vector(to_unsigned(0,12),12);
  constant mk_eoS: std_logic_vector(13 downto 0) := "10" & to_std_logic_vector(to_unsigned(0,12),12);
  function mk_data(d: signed(11 downto 0)) return std_logic_vector;
  function get_data(t: std_logic_vector) return signed;
end dc_s12;

library ieee,caph;
use ieee.std_logic_1164.all;
use caph.core.all;
use caph.data_types.all;
use ieee.numeric_std.all;

package dc_u8 is
  function is_soS(t: std_logic_vector) return boolean;
  function is_eoS(t: std_logic_vector) return boolean;
  function is_data(t: std_logic_vector) return boolean;
  constant mk_soS: std_logic_vector(9 downto 0) := "01" & to_std_logic_vector(to_unsigned(0,8),8);
  constant mk_eoS: std_logic_vector(9 downto 0) := "10" & to_std_logic_vector(to_unsigned(0,8),8);
  function mk_data(d: unsigned(7 downto 0)) return std_logic_vector;
  function get_data(t: std_logic_vector) return unsigned;
end dc_u8;


library ieee,caph;
use ieee.std_logic_1164.all;
use caph.core.all;
use caph.data_types.all;
use ieee.numeric_std.all;

package body dc_s12 is

  function is_soS(t: std_logic_vector) return boolean is
  begin
    return t(13 downto 12) = "01";
  end;

  function is_eoS(t: std_logic_vector) return boolean is
  begin
    return t(13 downto 12) = "10";
  end;

  function is_data(t: std_logic_vector) return boolean is
  begin
    return t(13 downto 12) = "11";
  end;

  function mk_data(d: signed(11 downto 0)) return std_logic_vector is
  begin
    return "11" & to_std_logic_vector(d,12);
  end;

  function get_data(t: std_logic_vector) return signed is
  begin
    return from_std_logic_vector(t(11 downto 0),12);
  end;

end package body dc_s12;

library ieee,caph;
use ieee.std_logic_1164.all;
use caph.core.all;
use caph.data_types.all;
use ieee.numeric_std.all;

package body dc_u8 is

  function is_soS(t: std_logic_vector) return boolean is
  begin
    return t(9 downto 8) = "01";
  end;

  function is_eoS(t: std_logic_vector) return boolean is
  begin
    return t(9 downto 8) = "10";
  end;

  function is_data(t: std_logic_vector) return boolean is
  begin
    return t(9 downto 8) = "11";
  end;

  function mk_data(d: unsigned(7 downto 0)) return std_logic_vector is
  begin
    return "11" & to_std_logic_vector(d,8);
  end;

  function get_data(t: std_logic_vector) return unsigned is
  begin
    return from_std_logic_vector(t(7 downto 0),8);
  end;

end package body dc_u8;


