-- -------------------------------------------------------------------------------
-- This file has been automatically generated by the Caph compiler (version 2.8.5)
-- from file main.cph, on 2020-05-06 at 15:29:19, by <unknown>
-- For more information, see : http://caph.univ-bpclermont.fr
-- -------------------------------------------------------------------------------

library ieee,caph;
use ieee.std_logic_1164.all;
use caph.core.all;
use caph.data_types.all;
use ieee.numeric_std.all;

package sobel_globals is
  type array3_s12 is array (0 to 2) of signed(11 downto 0);
  type array3_array3_s12 is array (0 to 2) of array3_s12;
  type array2_s12 is array (0 to 1) of signed(11 downto 0);
  type array3_array2_s12 is array (0 to 2) of array2_s12;
  type array3_b is array (0 to 2) of boolean;
  type array2_b is array (0 to 1) of boolean;
  type array3_array2_b is array (0 to 2) of array2_b;
  type array3_array3_b is array (0 to 2) of array3_b;
function fabs(x:signed(11 downto 0)) return signed;
end sobel_globals;

package body sobel_globals is
function fabs(x:signed(11 downto 0)) return signed is
  begin
    return cond((x) < (0),-(x),x);
  end fabs;
end sobel_globals;
