-- -------------------------------------------------------------------------------
-- This file has been automatically generated by the Caph compiler (version 2.8.5)
-- from file main.cph, on 2020-05-06 at 15:29:19, by <unknown>
-- For more information, see : http://caph.univ-bpclermont.fr
-- -------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;

entity split2 is
  generic ( size: integer := 10);
  port (  
       d_f:    out std_logic;
       d :     in std_logic_vector (size-1 downto 0);
       d_wr :  in std_logic;
       d1_f :  in std_logic;
       d1 :    out std_logic_vector(size-1 downto 0);
       d1_wr : out std_logic;
       d2_f :  in std_logic;
       d2 :    out std_logic_vector(size-1 downto 0);
       d2_wr : out std_logic
       );
end split2;


architecture arch of split2 is
begin
  d1 <= d;
  d2 <= d;
  d1_wr <= d_wr;
  d2_wr <= d_wr;
  d_f <= d1_f or d2_f;
end arch;


