-- -------------------------------------------------------------------------------
-- This file has been automatically generated by the Caph compiler (version 2.8.5)
-- from file main.cph, on 2020-05-06 at 15:29:19, by <unknown>
-- For more information, see : http://caph.univ-bpclermont.fr
-- -------------------------------------------------------------------------------

library ieee,caph,work;
use ieee.std_logic_1164.all;
use caph.core.all;
use caph.data_types.all;
use ieee.numeric_std.all;
use work.all;
use work.sobel_globals.all;

entity thr_act is
   generic (
    k: signed(11 downto 0)
    );
  port (
    i_empty: in std_logic;
    i: in std_logic_vector(13 downto 0);
    i_rd: out std_logic;
    o_full: in std_logic;
    o: out std_logic_vector(9 downto 0);
    o_wr: out std_logic;
    clock: in std_logic;
    reset: in std_logic
    );
end thr_act;

architecture FSM of thr_act is
begin
  comb: process(i, i_empty, o_full)
    variable p_p : signed(11 downto 0);
  begin
    -- i.rdy, i=SoS, o.rdy / rd(i), wr(o,SoS)
    if i_empty='0' and dc_s12.is_soS(i) and o_full='0' then
      i_rd <= '1';
      o <= dc_u8.mk_soS;
      o_wr <= '1';
    -- i.rdy, i=EoS, o.rdy / rd(i), wr(o,EoS)
    elsif i_empty='0' and dc_s12.is_eoS(i) and o_full='0' then
      i_rd <= '1';
      o <= dc_u8.mk_eoS;
      o_wr <= '1';
    -- i.rdy, i=Data(p_p), o.rdy / p_p=i.data, wr(o,if p_p>k then Data(255) else Data(0))
    elsif i_empty='0' and dc_s12.is_data(i) and o_full='0' then
      p_p := dc_s12.get_data(i);
      i_rd <= '1';
      if ( (p_p) > (k) ) then o <= dc_u8.mk_data(to_unsigned(255,8)); else o <= dc_u8.mk_data(to_unsigned(0,8)); end if;
      o_wr <= '1';
    else
      i_rd <= '0';
      o_wr <= '0';
      o <= (others => 'X');
    end if;
  end process;
  seq: process(clock, reset)
  begin
    if (reset='0') then
    elsif rising_edge(clock) then
    end if;
  end process;
end FSM;
