-- -------------------------------------------------------------------------------
-- This file has been automatically generated by the Caph compiler (version 2.8.5)
-- from file main.cph, on 2020-05-08 at 00:10:27, by <unknown>
-- For more information, see : http://caph.univ-bpclermont.fr
-- -------------------------------------------------------------------------------

library ieee,caph;
use ieee.std_logic_1164.all;
use caph.core.all;
use caph.data_types.all;
use ieee.numeric_std.all;

entity conv33_v1_tb is
end conv33_v1_tb;

architecture arch of conv33_v1_tb is

component conv33_v1_net is
  port (
    w42_f: out std_logic;
    w42: in std_logic_vector(17 downto 0);
    w42_wr: in std_logic;
    w92_e: out std_logic;
    w92: out std_logic_vector(17 downto 0);
    w92_rd: in std_logic;
    w134_e: out std_logic;
    w134: out std_logic_vector(17 downto 0);
    w134_rd: in std_logic;
    clock: in std_logic;
    reset: in std_logic
    );
end component;

signal w134_e : std_logic;
signal w134 : std_logic_vector(17 downto 0);
signal w134_rd : std_logic;
signal w92_e : std_logic;
signal w92 : std_logic_vector(17 downto 0);
signal w92_rd : std_logic;
signal w42_f : std_logic;
signal w42 : std_logic_vector(17 downto 0);
signal w42_wr : std_logic;
signal clock: std_logic;
signal reset: std_logic;

begin
  B3: stream_out generic map ("result2.bin",18) port map(w134_e,w134,w134_rd,clock,reset);
  B2: stream_out generic map ("result1.bin",18) port map(w92_e,w92,w92_rd,clock,reset);
  B1: stream_in generic map ("lena64.bin",18,1,false,0 ns) port map(w42_f,w42,w42_wr,clock,reset);
  N: conv33_v1_net port map(w42_f,w42,w42_wr,w92_e,w92,w92_rd,w134_e,w134,w134_rd,clock,reset);

process                     -- Initial reset
begin
  reset <= '0';
  wait for 1 ns;
  reset <= '1';
  wait;
end process;

process                     -- Clock
begin
  clock <= '1';
  wait for 5 ns;
  clock <= '0';
  wait for 5 ns;
end process;

end arch;
