-- -------------------------------------------------------------------------------
-- This file has been automatically generated by the Caph compiler (version 2.8.5)
-- from file main.cph, on 2020-05-08 at 00:10:27, by <unknown>
-- For more information, see : http://caph.univ-bpclermont.fr
-- -------------------------------------------------------------------------------

library ieee,caph;
use ieee.std_logic_1164.all;
use caph.core.all;
use caph.data_types.all;
use ieee.numeric_std.all;

package dc_s16 is
  function is_soS(t: std_logic_vector) return boolean;
  function is_eoS(t: std_logic_vector) return boolean;
  function is_data(t: std_logic_vector) return boolean;
  constant mk_soS: std_logic_vector(17 downto 0) := "01" & to_std_logic_vector(to_unsigned(0,16),16);
  constant mk_eoS: std_logic_vector(17 downto 0) := "10" & to_std_logic_vector(to_unsigned(0,16),16);
  function mk_data(d: signed(15 downto 0)) return std_logic_vector;
  function get_data(t: std_logic_vector) return signed;
end dc_s16;


library ieee,caph;
use ieee.std_logic_1164.all;
use caph.core.all;
use caph.data_types.all;
use ieee.numeric_std.all;

package body dc_s16 is

  function is_soS(t: std_logic_vector) return boolean is
  begin
    return t(17 downto 16) = "01";
  end;

  function is_eoS(t: std_logic_vector) return boolean is
  begin
    return t(17 downto 16) = "10";
  end;

  function is_data(t: std_logic_vector) return boolean is
  begin
    return t(17 downto 16) = "11";
  end;

  function mk_data(d: signed(15 downto 0)) return std_logic_vector is
  begin
    return "11" & to_std_logic_vector(d,16);
  end;

  function get_data(t: std_logic_vector) return signed is
  begin
    return from_std_logic_vector(t(15 downto 0),16);
  end;

end package body dc_s16;


